/**
 * PM2 Frontend Applications Configuration
 * 
 * Manages all frontend Next.js applications
 * 
 * Usage:
 *   pm2 start ecosystem.frontend.config.js              # Start all frontend apps
 *   pm2 start ecosystem.frontend.config.js --only frontend-admin  # Start specific app
 *   pm2 stop ecosystem.frontend.config.js               # Stop all frontend apps
 *   pm2 restart ecosystem.frontend.config.js            # Restart all frontend apps
 *   pm2 logs                                            # View all logs
 *   pm2 logs frontend-admin                             # View specific app logs
 *   pm2 monit                                           # Monitor dashboard
 *   pm2 delete ecosystem.frontend.config.js             # Delete all frontend apps
 */

module.exports = {
  apps: [
    // ============================================
    // Frontend Applications
    // ============================================
    {
      name: 'frontend-admin',
      script: 'npm',
      args: 'run dev -- -p 3078',
      cwd: './frontend/admin',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3078,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
        NEXT_PUBLIC_DEMO_TENANT_ID: '11111111-2222-3333-4444-555555555555',
        NEXT_PUBLIC_DEMO_BEARER_TOKEN: 'demo-admin-token',
      },
      error_file: './.logs/frontend/frontend-admin-error.log',
      out_file: './.logs/frontend/frontend-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-marketing',
      script: 'npm',
      args: 'run dev -- -p 3074',
      cwd: './frontend/marketing',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      env: {
        NODE_ENV: 'development',
        PORT: 3074,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-marketing-error.log',
      out_file: './.logs/frontend/frontend-marketing-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-console',
      script: 'npm',
      args: 'run dev -- -p 3076',
      cwd: './frontend/console',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      env: {
        NODE_ENV: 'development',
        PORT: 3076,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-console-error.log',
      out_file: './.logs/frontend/frontend-console-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-analytics',
      script: 'npm',
      args: 'run dev -- -p 3094',
      cwd: './frontend/analytics',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3094,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-analytics-error.log',
      out_file: './.logs/frontend/frontend-analytics-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-billing',
      script: 'npm',
      args: 'run dev -- -p 3092',
      cwd: './frontend/billing',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3092,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-billing-error.log',
      out_file: './.logs/frontend/frontend-billing-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-hrms',
      script: 'npm',
      args: 'run dev -- -p 3084',
      cwd: './frontend/hrms',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3084,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-hrms-error.log',
      out_file: './.logs/frontend/frontend-hrms-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-crm',
      script: 'npm',
      args: 'run dev -- -p 3090',
      cwd: './frontend/crm',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3090,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-crm-error.log',
      out_file: './.logs/frontend/frontend-crm-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-fbms',
      script: 'npm',
      args: 'run dev -- -p 3088',
      cwd: './frontend/fbms',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3088,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-fbms-error.log',
      out_file: './.logs/frontend/frontend-fbms-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-builder',
      script: 'npm',
      args: 'run dev -- -p 3080',
      cwd: './frontend/builder',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3080,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-builder-error.log',
      out_file: './.logs/frontend/frontend-builder-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-compliance',
      script: 'npm',
      args: 'run dev -- -p 3096',
      cwd: './frontend/compliance',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3096,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-compliance-error.log',
      out_file: './.logs/frontend/frontend-compliance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-ems',
      script: 'npm',
      args: 'run dev -- -p 3098',
      cwd: './frontend/ems',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3098,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-ems-error.log',
      out_file: './.logs/frontend/frontend-ems-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-forms',
      script: 'npm',
      args: 'run dev -- -p 3082',
      cwd: './frontend/forms',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3082,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-forms-error.log',
      out_file: './.logs/frontend/frontend-forms-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-inventory',
      script: 'npm',
      args: 'run dev -- -p 3100',
      cwd: './frontend/inventory',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3100,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-inventory-error.log',
      out_file: './.logs/frontend/frontend-inventory-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-scm',
      script: 'npm',
      args: 'run dev -- -p 3102',
      cwd: './frontend/scm',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3102,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-scm-error.log',
      out_file: './.logs/frontend/frontend-scm-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-support',
      script: 'npm',
      args: 'run dev -- -p 3104',
      cwd: './frontend/support',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3104,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-support-error.log',
      out_file: './.logs/frontend/frontend-support-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-vouchers',
      script: 'npm',
      args: 'run dev -- -p 3086',
      cwd: './frontend/vouchers',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'development',
        PORT: 3086,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
      },
      error_file: './.logs/frontend/frontend-vouchers-error.log',
      out_file: './.logs/frontend/frontend-vouchers-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    // DISABLED: frontend-mobile (uncomment to enable)
    // {
    //   name: 'frontend-mobile',
    //   script: 'npm',
    //   args: 'run dev',
    //   cwd: './frontend/mobile',
    //   instances: 1,
    //   autorestart: true,
    //   watch: false,
    //   max_memory_restart: '600M',
    //   env: {
    //     NODE_ENV: 'development',
    //     PORT: 4219,
    //     NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:3010',
    //   },
    //   error_file: './.logs/frontend/frontend-mobile-error.log',
    //   out_file: './.logs/frontend/frontend-mobile-out.log',
    //   log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    //   merge_logs: true,
    //   time: true,
    // },
  ],
};

