/**
 * PM2 Ecosystem Configuration
 * 
 * Manages all backend microservices and frontend applications
 * 
 * Usage:
 *   pm2 start ecosystem.config.js              # Start all services
 *   pm2 start ecosystem.config.js --only api-gateway  # Start specific service
 *   pm2 start ecosystem.config.js --only backend      # Start all backend services
 *   pm2 start ecosystem.config.js --only frontend     # Start all frontend apps
 *   pm2 stop all                                    # Stop all services
 *   pm2 restart all                                 # Restart all services
 *   pm2 logs                                        # View all logs
 *   pm2 monit                                       # Monitor dashboard
 */

module.exports = {
  apps: [
    // ============================================
    // Backend Services (Critical - Start First)
    // ============================================
    {
      name: 'api-gateway',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/api-gateway',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4000,
      },
      error_file: './.logs/api-gateway-error.log',
      out_file: './.logs/api-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'identity-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/identity-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: './backend/services/identity-service/.env',
      env: {
        NODE_ENV: 'development',
        PORT: 4001,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
        JWT_ACCESS_SECRET: 'Keephy1234Access1234Secret123456789',
        JWT_REFRESH_SECRET: 'Keephy1234Access1234Secret123456789',
        ACCESS_TOKEN_TTL: '900',
        REFRESH_TOKEN_TTL: '2592000',
        BCRYPT_SALT_ROUNDS: '10',
        ACCESS_SERVICE_URL: 'http://localhost:4002',
        SUBSCRIPTIONS_SERVICE_URL: 'http://localhost:4010',
        TENANT_SERVICE_URL: 'http://localhost:4033',
      },
      error_file: './.logs/identity-service-error.log',
      out_file: './.logs/identity-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'access-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/access-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4002,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/access-service-error.log',
      out_file: './.logs/access-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },

    // ============================================
    // Backend Services (Core Services)
    // ============================================
    {
      name: 'admin-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/admin-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: './backend/services/admin-service/.env',
      env: {
        NODE_ENV: 'development',
        PORT: 4028,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/admin-service-error.log',
      out_file: './.logs/admin-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'media-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/media-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4003,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/media-service-error.log',
      out_file: './.logs/media-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'contacts-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/contacts-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4004,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/contacts-service-error.log',
      out_file: './.logs/contacts-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'notifications-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/notifications-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4005,
      },
      error_file: './.logs/notifications-service-error.log',
      out_file: './.logs/notifications-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'audit-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/audit-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4006,
      },
      error_file: './.logs/audit-service-error.log',
      out_file: './.logs/audit-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },

    // ============================================
    // Backend Services (Business Services)
    // ============================================
    {
      name: 'billing-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/billing-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4012,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/billing-service-error.log',
      out_file: './.logs/billing-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'hrms-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/hrms-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4015,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/hrms-service-error.log',
      out_file: './.logs/hrms-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'analytics-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/analytics-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4021,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/analytics-service-error.log',
      out_file: './.logs/analytics-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'crm-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/crm-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4018,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/crm-service-error.log',
      out_file: './.logs/crm-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ai-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/ai-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4029,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/ai-service-error.log',
      out_file: './.logs/ai-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'payroll-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/payroll-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4016,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/payroll-service-error.log',
      out_file: './.logs/payroll-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'subscriptions-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/subscriptions-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4010,
      },
      error_file: './.logs/subscriptions-service-error.log',
      out_file: './.logs/subscriptions-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'entitlements-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/entitlements-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4011,
      },
      error_file: './.logs/entitlements-service-error.log',
      out_file: './.logs/entitlements-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'compliance-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/compliance-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4020,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/compliance-service-error.log',
      out_file: './.logs/compliance-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ems-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/ems-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4022,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/ems-service-error.log',
      out_file: './.logs/ems-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'facilities-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/facilities-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4015,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/facilities-service-error.log',
      out_file: './.logs/facilities-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'onboarding-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/onboarding-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4027,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/onboarding-service-error.log',
      out_file: './.logs/onboarding-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'integration-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/integration-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4031,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/integration-service-error.log',
      out_file: './.logs/integration-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'lifecycle-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/lifecycle-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4030,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/lifecycle-service-error.log',
      out_file: './.logs/lifecycle-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'mobile-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/mobile-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 4032,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/mobile-service-error.log',
      out_file: './.logs/mobile-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },

    // ============================================
    // Frontend Applications
    // ============================================
    {
      name: 'frontend-admin',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend/admin',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_file: './frontend/admin/.env.local',
      env: {
        NODE_ENV: 'development',
        PORT: 4205,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:4000',
        NEXT_PUBLIC_DEMO_TENANT_ID: '11111111-2222-3333-4444-555555555555',
        NEXT_PUBLIC_DEMO_BEARER_TOKEN: 'demo-admin-token',
      },
      error_file: './.logs/frontend-admin-error.log',
      out_file: './.logs/frontend-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-marketing',
      script: 'npm',
      args: 'run dev -- -p 4200',
      cwd: './frontend/marketing',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4200,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:4000',
      },
      error_file: './.logs/frontend-marketing-error.log',
      out_file: './.logs/frontend-marketing-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-analytics',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend/analytics',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4206,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:4000',
      },
      error_file: './.logs/frontend-analytics-error.log',
      out_file: './.logs/frontend-analytics-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-billing',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend/billing',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4207,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:4000',
      },
      error_file: './.logs/frontend-billing-error.log',
      out_file: './.logs/frontend-billing-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-hrms',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend/hrms',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4213,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:4000',
      },
      error_file: './.logs/frontend-hrms-error.log',
      out_file: './.logs/frontend-hrms-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'frontend-crm',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend/crm',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 4209,
        NEXT_PUBLIC_GATEWAY_URL: 'http://localhost:4000',
      },
      error_file: './.logs/frontend-crm-error.log',
      out_file: './.logs/frontend-crm-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
  ],
};

