/**
 * PM2 Backend Services Configuration
 * 
 * Manages all backend microservices
 * 
 * Usage:
 *   pm2 start ecosystem.backend.config.js              # Start all backend services
 *   pm2 start ecosystem.backend.config.js --only api-gateway  # Start specific service
 *   pm2 stop ecosystem.backend.config.js               # Stop all backend services
 *   pm2 restart ecosystem.backend.config.js            # Restart all backend services
 *   pm2 logs                                           # View all logs
 *   pm2 logs api-gateway                               # View specific service logs
 *   pm2 monit                                          # Monitor dashboard
 *   pm2 delete ecosystem.backend.config.js             # Delete all backend services
 */

module.exports = {
  apps: [
    // ============================================
    // Critical Backend Services (Start First)
    // ============================================
    {
      name: 'api-gateway',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/api-gateway',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3010,
        IDENTITY_SERVICE_URL: 'http://localhost:3012',
        ACCESS_SERVICE_URL: 'http://localhost:3014',
        TENANT_SERVICE_URL: 'http://localhost:3016',
        MEDIA_SERVICE_URL: 'http://localhost:3018',
        FBMS_SERVICE_URL: 'http://localhost:3020',
        CONTACTS_SERVICE_URL: 'http://localhost:3022',
        NOTIFICATIONS_SERVICE_URL: 'http://localhost:3024',
        AUDIT_SERVICE_URL: 'http://localhost:3026',
        SUBSCRIPTIONS_SERVICE_URL: 'http://localhost:3028',
        ENTITLEMENTS_SERVICE_URL: 'http://localhost:3030',
        BILLING_SERVICE_URL: 'http://localhost:3032',
        OBSERVABILITY_SERVICE_URL: 'http://localhost:3034',
        HRMS_SERVICE_URL: 'http://localhost:3036',
        SCM_SERVICE_URL: 'http://localhost:3038',
        PAYROLL_SERVICE_URL: 'http://localhost:3040',
        INVENTORY_SERVICE_URL: 'http://localhost:3042',
        CRM_SERVICE_URL: 'http://localhost:3044',
        SUPPORT_SERVICE_URL: 'http://localhost:3046',
        COMPLIANCE_SERVICE_URL: 'http://localhost:3048',
        ANALYTICS_SERVICE_URL: 'http://localhost:3050',
        EMS_SERVICE_URL: 'http://localhost:3052',
        VOUCHER_SERVICE_URL: 'http://localhost:3054',
        FORMS_SERVICE_URL: 'http://localhost:3056',
        BUILDER_SERVICE_URL: 'http://localhost:3058',
        ONBOARDING_SERVICE_URL: 'http://localhost:3060',
        ADMIN_SERVICE_URL: 'http://localhost:3062',
        AI_SERVICE_URL: 'http://localhost:3064',
        LIFECYCLE_SERVICE_URL: 'http://localhost:3066',
        INTEGRATION_SERVICE_URL: 'http://localhost:3068',
        MOBILE_SERVICE_URL: 'http://localhost:3070',
        FACILITIES_SERVICE_URL: 'http://localhost:3072',
      },
      error_file: './.logs/backend/api-gateway-error.log',
      out_file: './.logs/backend/api-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'identity-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/identity-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3012,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
        JWT_ACCESS_SECRET: 'Keephy1234Access1234Secret123456789',
        JWT_REFRESH_SECRET: 'Keephy1234Access1234Secret123456789',
        ACCESS_TOKEN_TTL: '900',
        REFRESH_TOKEN_TTL: '2592000',
        BCRYPT_SALT_ROUNDS: '10',
        ACCESS_SERVICE_URL: 'http://localhost:3014',
        SUBSCRIPTIONS_SERVICE_URL: 'http://localhost:3028',
        NOTIFICATIONS_SERVICE_URL: 'http://localhost:3024',
        PASSWORD_RESET_TTL: '3600',
        PASSWORD_RESET_BASE_URL: 'http://localhost:3000/reset-password',
        TENANT_SERVICE_URL: 'http://localhost:3016',
      },
      error_file: './.logs/backend/identity-service-error.log',
      out_file: './.logs/backend/identity-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'access-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/access-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3014,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/access-service-error.log',
      out_file: './.logs/backend/access-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'tenant-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/tenant-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3016,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
        ACCESS_SERVICE_URL: 'http://localhost:3014',
        TENANT_SERVICE_URL: 'http://localhost:3016',
      },
      error_file: './.logs/backend/tenant-service-error.log',
      out_file: './.logs/backend/tenant-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },

    // ============================================
    // Core Backend Services
    // ============================================
    {
      name: 'admin-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/admin-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3062,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/admin-service-error.log',
      out_file: './.logs/backend/admin-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'media-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/media-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3018,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/media-service-error.log',
      out_file: './.logs/backend/media-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'contacts-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/contacts-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3022,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/contacts-service-error.log',
      out_file: './.logs/backend/contacts-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'notifications-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/notifications-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3024,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/notifications-service-error.log',
      out_file: './.logs/backend/notifications-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'audit-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/audit-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3026,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/audit-service-error.log',
      out_file: './.logs/backend/audit-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },

    // ============================================
    // Business Domain Services
    // ============================================
    {
      name: 'billing-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/billing-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3032,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/billing-service-error.log',
      out_file: './.logs/backend/billing-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'hrms-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/hrms-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3036,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/hrms-service-error.log',
      out_file: './.logs/backend/hrms-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'analytics-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/analytics-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3050,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/analytics-service-error.log',
      out_file: './.logs/backend/analytics-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'crm-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/crm-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3044,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/crm-service-error.log',
      out_file: './.logs/backend/crm-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ai-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/ai-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3064,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/ai-service-error.log',
      out_file: './.logs/backend/ai-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'payroll-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/payroll-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3040,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/payroll-service-error.log',
      out_file: './.logs/backend/payroll-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'subscriptions-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/subscriptions-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3028,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/subscriptions-service-error.log',
      out_file: './.logs/backend/subscriptions-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'entitlements-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/entitlements-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3030,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/entitlements-service-error.log',
      out_file: './.logs/backend/entitlements-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'compliance-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/compliance-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3048,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/compliance-service-error.log',
      out_file: './.logs/backend/compliance-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ems-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/ems-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3052,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/ems-service-error.log',
      out_file: './.logs/backend/ems-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'facilities-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/facilities-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3072,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/facilities-service-error.log',
      out_file: './.logs/backend/facilities-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'onboarding-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/onboarding-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3060,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/onboarding-service-error.log',
      out_file: './.logs/backend/onboarding-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'integration-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/integration-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3068,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/integration-service-error.log',
      out_file: './.logs/backend/integration-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'lifecycle-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/lifecycle-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3066,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/lifecycle-service-error.log',
      out_file: './.logs/backend/lifecycle-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'mobile-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/mobile-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3070,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/mobile-service-error.log',
      out_file: './.logs/backend/mobile-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'fbms-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/fbms-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3020,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/fbms-service-error.log',
      out_file: './.logs/backend/fbms-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'builder-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/builder-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3058,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/builder-service-error.log',
      out_file: './.logs/backend/builder-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'forms-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/forms-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3056,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/forms-service-error.log',
      out_file: './.logs/backend/forms-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'inventory-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/inventory-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3042,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/inventory-service-error.log',
      out_file: './.logs/backend/inventory-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'scm-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/scm-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3038,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/scm-service-error.log',
      out_file: './.logs/backend/scm-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'support-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/support-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3046,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/support-service-error.log',
      out_file: './.logs/backend/support-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    {
      name: 'voucher-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/voucher-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3054,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/voucher-service-error.log',
      out_file: './.logs/backend/voucher-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
    // DISABLED: migration-service (utility service - run migration scripts manually)
    // Use: npm run migrate:all from backend/services/migration-service directory
    // {
    //   name: 'migration-service',
    //   script: 'npm',
    //   args: 'run start:dev',
    //   cwd: './backend/services/migration-service',
    //   instances: 1,
    //   autorestart: true,
    //   watch: false,
    //   max_memory_restart: '300M',
    //   env: {
    //     NODE_ENV: 'development',
    //     PORT: 4025,
    //     DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
    //   },
    //   error_file: './.logs/backend/migration-service-error.log',
    //   out_file: './.logs/backend/migration-service-out.log',
    //   log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    //   merge_logs: true,
    //   time: true,
    // },
    {
      name: 'observability-service',
      script: 'npm',
      args: 'run start:dev',
      cwd: './backend/services/observability-service',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: 3034,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/hrmssystem',
      },
      error_file: './.logs/backend/observability-service-error.log',
      out_file: './.logs/backend/observability-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
  ],
};

